services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    container_name: app
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pg_data:
