"""set some fields in table movies nullable

Revision ID: 0b6822dd1621
Revises: beb07cfbd990
Create Date: 2025-01-15 19:11:32.129718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6822dd1621'
down_revision: Union[str, None] = 'beb07cfbd990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('movies', 'cast',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('movies', 'date_added',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('movies', 'rating',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'rating',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('movies', 'date_added',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('movies', 'cast',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
