"""set show_id unique

Revision ID: 61a5194a6dcb
Revises: 0b6822dd1621
Create Date: 2025-01-16 08:48:09.752438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a5194a6dcb'
down_revision: Union[str, None] = '0b6822dd1621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['show_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
