"""delete max length from cast field

Revision ID: b47de990792d
Revises: bf0933533c03
Create Date: 2025-01-16 09:29:32.315859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47de990792d'
down_revision: Union[str, None] = 'bf0933533c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'cast',
                    type_=sa.String(),
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'cast',
                    existing_type=sa.VARCHAR(length=500),
                    nullable=True)
    # ### end Alembic commands ###
